Automation task 6
dgrimaliuc/tekwill-automation-project pull request #26
Opened 2023-07-18 16:44 UTC by LiudaL

Automation task #6

2023-07-20 07:26 UTC, dgrimaliuc-crunchyroll commented on src/test/java/Leas_Liudmila/junit/FirstJUnitTask.java
> +    @ParameterizedTest
no need to use ParameterizedTest where is only one parameter

2023-07-24 08:20 UTC, dgrimaliuc requested changes

2023-07-24 08:20 UTC, dgrimaliuc commented on src/test/java/Leas_Liudmila/junit/FirstJUnitTask.java
> +    @ParameterizedTest
no need to use ParameterizedTest where is only one parameter

2023-07-24 13:49 UTC, dgrimaliuc-crunchyroll approved these changes

2023-07-24 13:50 UTC, dgrimaliuc approved these changes

2023-07-24 14:08 UTC, merged