VictorMurashev-homework-20240804
dgrimaliuc/tekwill-automation-project pull request #70
Opened 2024-08-04 19:30 UTC by vmurashev365

2024-08-06 08:48 UTC, dgrimaliuc-crunchyroll commented on pom.xml
> +            <version>2.8.9</version>
don't touch versions, return it back

2024-08-06 17:04 UTC, vmurashev365 commented on pom.xml
> +            <version>2.8.9</version>
> don't touch versions, return it back

@dgrimaliuc done

2024-08-07 08:58 UTC, dgrimaliuc-crunchyroll requested changes

2024-08-07 08:58 UTC, dgrimaliuc-crunchyroll commented on src/test/java/denis_grimaliuc/step_definitions/UIStepDefinition.java
> +    public void shopify_page_is_open() {
my file should not be changed

2024-08-12 06:52 UTC, dgrimaliuc commented
please resolve conflicts

2024-08-12 06:52 UTC, dgrimaliuc-crunchyroll submitted a review, later dismissed

2024-08-16 08:15 UTC, closed without merging